voxpupuli/puppet-selinux

manifests/config.pp
The original route is a symbolic link, is better to replace the value on the original file. I've found some boxes where the symbolic link does not exist and the module fails
=> REPLACE config file route

manifests/module.pp
Without the quotes, Puppet 3.7 breaks.
=> reverting previous lint change

manifests/config.pp
If selinux is disabled, setenforce will fail when trying to change the status. This can be changed only with a reboot.
=> fix change-selinux-status in case of selinux disabled

manifests/params.pp
Since Facter 2.2 you can use $operatingsystemmajrelease which avoids the stupid numbering used by CentOS 7 and means you don't have to match a regex
=> Better compatibility with CentOS 7

manifests/config.pp
If selinux is disabled, the $::selinux_current_mode variable is undefined and throws an error when run with strict_variables=true
Getting the value with getvar fixes this.
=> Fix to work with strict_variables=true

manifests/config.pp
I got into a discussion with @richardc about strict_variables and getvar.
tl;dr: use "defined" not "getvar" to protect against undefined variables.
=> Use "defined" instead of "getvar" to protect against undefined variables when strict_variables=yes

lib/facter/selinux_custom_policy.rb, manifests/module.pp
Small workaround to fix the module running on RH 7 variants, detailed in [issue 27](https://github.com/jfryman/puppet-selinux/issues/27)
Provide a new custom fact that will only execute on RH 7 variants with SELinux enabled, and use that to determine the policy in module.pp if the default selinux_config_policy fact is not either 'targeted' or 'strict'.
=> Workaround for RH 7 variants

manifests/module.pp, metadata.json
Hello Mr. Fryman
I recently began using trying out this module, and ran into a peculiar issue. When I try to have two selinux::module declarations get applied to the same host (which should be possible, seeing as how it's a defined type), I get catalog cycle dependency errors. Having multiple selinux::module types defined in such a way that one is dependent on the other (such as having them in separate profile manifests where other contents of the profile require ordering at the role manifest level) appears to be the trigger for the issue. Having read the type definition and thinking about it a bit, I believe the root issue is the way you used tags in the file declarations. While it's a neat trick to work around not knowing if you'll have a .mod file declaration ahead of time, you don't …
=> Bug fix for declaring multiple selinux::module types

manifests/permissive.pp
Run 'semanage permissive -a' to set a context to permissive.
I use this to allow oddjob_mkhomedir_t to create home directories upon login if they do not exist.
I am not a puppet developer, so if I missed something, please review it.
=> Add Permissive to puppet-selinux module

manifests/params.pp
Hello,
we use the new Sattelite 6.1 with Red Hat supported puppet packages.
For RHEL5, the package version is 2.7.23.
The facter operatingsystemmajrelease is named on 2.7.X, a simply fallback to lsbmajdistrelease is used, if the operatingsystemmajrelease is empty.
=> Fallback to lsbmajdistrelease, if puppet version is < 3.0

manifests/module.pp, spec/defines/selinux_module_spec.rb, spec/spec_helper.rb
Before this, selinux::module ensure => 'absent' would fail because:
- Exec["${name}-buildmod"] wouldn't be created
- Exec["${name}-checkloaded"] therefore couldn't notify it
Also:
- Add rspec testing for selinux::module
- Add custom fact selinux_config_policy to spec_helper
=> Fix for selinux::module absent case failed notify

README.markdown, manifests/config.pp, manifests/init.pp, manifests/package.pp, manifests/params.pp, spec/classes/selinux_package_spec.rb
=> Allow custom package name and management

manifests/port.pp, spec/defines/selinux_port_spec.rb
If you have the same port allowed on both udp & tcp the puppet manifest
will fail as you have a duplicate name, this change adds the protocol
name into port definition
=> Make port exec statement unique for protocol

.travis.yml, Gemfile, Rakefile, lib/facter/selinux_custom_policy.rb, manifests/boolean.pp, manifests/config.pp, manifests/init.pp, manifests/module.pp, manifests/package.pp, manifests/params.pp, spec/classes/selinux_config_mode_spec.rb, spec/classes/selinux_config_type_spec.rb, spec/classes/selinux_package_spec.rb, spec/classes/selinux_restorecond_config_spec.rb, spec/classes/selinux_restorecond_service_spec.rb, spec/classes/selinux_restorecond_spec.rb, spec/classes/selinux_spec.rb, spec/defines/selinux_boolean_spec.rb, spec/defines/selinux_fcontext_spec.rb, spec/defines/selinux_module_spec.rb, spec/defines/selinux_port_spec.rb, spec/defines/selinux_restorecond_fragment_spec.rb, spec/spec_helper.rb
=> Pivot to internal types

lib/facter/selinux_custom_policy.rb
Fixing the issue as suggested by @sharkannon.
Tested on EL7
```
CentOS Linux release 7.2.1511 (Core)
```
```
rubygem-json-1.7.7-25.el7_1.x86_64
ruby-irb-2.0.0.598-25.el7_1.noarch
rubygem-bigdecimal-1.2.0-25.el7_1.x86_64
rubygem-io-console-0.4.2-25.el7_1.x86_64
ruby-shadow-2.2.0-2.el7.x86_64
ruby-augeas-0.5.0-1.el7.x86_64
libselinux-ruby-2.2.2-6.el7.x86_64
ruby-libs-2.0.0.598-25.el7_1.x86_64
rubygem-rdoc-4.0.0-25.el7_1.noarch
ruby-2.0.0.598-25.el7_1.x86_64
rubygem-psych-2.0.0-25.el7_1.x86_64
rubygems-2.0.14-25.el7_1.noarch
facter-2.4.4-1.el7.x86_64
puppet-3.8.4-1.el7.noarch`
```
and EL6 clients.
```
CentOS release 6.7 (Final)
```
```
[root@el6testclient01 ~]# rpm -qa | grep -E 'puppet|facter|ruby'
ruby-libs-1.8.7.374-4.el6_6.x86_64
ruby-rdoc-1.8.7.374-4.el6_6.x86_64 …
```
=> Fix Issue #76

manifests/module.pp
In Fedora 23, the semodule -l option doesn't return the module list anymore, and semodule --upgrade reports that it is upgraded (to use --install instead).  So this patch makes syncversion a parameter to the selinux::module type, defaulting it to true.
=> Add syncversion parameter

manifests/fcontext.pp, spec/defines/selinux_fcontext_spec.rb
The fcontext defined type sets the permanent state, but you still have to run restorecon to actually make that change take effect.   This is a proposal that by default will always run restorecon on the pathname (unless disabled with the $restorecond = false flag set)
Happy to look at better ways of doing this, but I wanted to be able to make the changes take effect without having to take a second step in puppet.
=> Added support for running restorecon after modifying file contexts

manifests/module.pp, spec/defines/selinux_module_spec.rb
The fix changes the module name that is provided for selmodule from
${prefix}${name} to $name. The module shouldn't reload selinux module
anymore on every run as now selinux module name matches with the name
provided.
Should fix #90
=> Fix module installation

lib/facter/selinux_custom_policy.rb, manifests/config.pp, manifests/fcontext.pp, manifests/module.pp, manifests/permissive.pp, manifests/port.pp, spec/defines/selinux_fcontext_spec.rb, spec/defines/selinux_module_spec.rb, spec/defines/selinux_port_spec.rb, spec/defines/selinux_restorecond_fragment_spec.rb
This patchset contains several small cleanups. It also contains fixes for #105 and #108 from TJM. Those issues do have some issue with travis and have not gone forward. As both issues are something I'd like to have and also have further changes in shellquote part, I've added them here.
=> Cleanups and dangling issues

manifests/params.pp
We had an issue with Amazon Linux servers. This fix is for avoiding the legend 'Operating system is not supported'
=> Fixing operatingsystem for Amazon Linux

CHANGELOG.md, manifests/params.pp, metadata.json
=> Release 0.5.0

manifests/params.pp
Fedora 25 is (well, will be, once it's officially released) basically the same as Fedora 24, as far as puppet-selinux is concerned, so here's a quick update to keep it from erroring out. :smiley:
=> params.pp needs to know about Fedora 25

manifests/init.pp
Hiera hash are managed only if they exist 
+ hiera lookups outside of the variables part of the manifest.
=> Fixes Issue-104 - No Hiera support

README.md
Your Mileage **won't** Vary.  Ruby 1.8 will not work.  See https://github.com/voxpupuli/puppet-selinux/commit/d4ea1c622fff501ee6a65a1c15dcbc599cac4b14
=> Update README with ruby 1.8 status

manifests/fcontext.pp, spec/defines/selinux_fcontext_spec.rb
The command
```bash
semanage fcontext -a -f a -t httpd_tmp_t /usr/share/nginx
```
fails on RHEL6 machines. This changes it to
```bash
semanage fcontext -a -f 'all files' -t httpd_tmp_t /usr/share/nginx
```
* https://github.com/voxpupuli/puppet-selinux/issues/133
=> Fixes #133 Use semange -f 'all files' on RHEL6

metadata.json
Also bump minimum version for stdlib (for Puppet 4) and fix invalid version_range key
=> Set puppet minimum version_requirement to 3.8.7

spec/acceptance/class_spec.rb, spec/spec_helper_acceptance.rb
This PR adds a simple acceptance test scenario.
It will:
* enable selinux
* set it to enforcing
* load a custom policy with a custom domain, boolean and file and port
contexts
* enable a custom boolean
* label a port with a custom context
* set a custom context on a file and 
* it will set the custom domain into permissive mode
Run `PUPPET_INSTALL_TYPE=agent bundle exec rake beaker:centos-72-x64` to
test with CentOS 7.
Run `PUPPET_INSTALL_TYPE=agent bundle exec rake beaker:centos-66-x64` to
test with CentOS 6.
There is a known problem with CentOS 7 and the selmodule type. See 
PUP-6908, PUP-5649
=> Add acceptance tests

manifests/config.pp, spec/classes/selinux_config_mode_spec.rb, spec/default_module_facts.yml
A complete relabeling is required when switching from disabeld to
permissive or enforcing mode, because selinux file attributes
are not written in disabled mode this leaving the files regarding
selinux in an incosistent state.
This resolves #149
=> Create /.autorelabel when switching from disabled

manifests/module.pp, spec/defines/selinux_module_spec.rb
With RHEL7.3 the default module prefix causes problems
in particular the following happens
with
```puppet
selinux::module { 'openshift-cvmfs':
ensure => present,
source => 'puppet:///modules/hg_paas/openshift-cvmfs.te',
}
```
```
Compiling targeted local_openshift-cvmfs module
/usr/bin/checkmodule:  loading policy configuration from
tmp/local_openshift-cvmfs.tmp
/usr/bin/checkmodule:  Module name openshift-cvmfs is different than the
output base filename local_openshift-cvmfs
make: *** [tmp/local_openshift-cvmfs.mod] Error 1
```
As far as I can ascertain the prefix only influences the file name
and actual module name comes from what's inside the policy file.
Anyone testing this may well runinto another selinux bug that
is not a problem of this module.
* [CERN ticket …
=> Default module prefix now ''

README.md
Ruby 1.9.3 is EOL, regardless of where it may be bundled.
Avoid mentions of specific Ruby versions
Also remove mentions of specific Facter versions
=> Remove mentions of Ruby requirements in README

manifests/module.pp
Newer SELinux tools don't show the modules version number when
calling `semodule -l`. Unfortunatly there is a bug in puppet's
selmodule type which leads to re-applying the resource every
time even when syncversion is false. Only undef works.
This change defaults the syncversion parameter to undef instead
of true.
This fixes the repeated change:
```
Selmodule[puppet_selinux_test_policy]/syncversion: syncversion changed 'false' to 'true'
```
See also: PUP-6908, PUP-5649
Succesfully ran centos-72-x64 and centos-66-x64 acceptance tests.
=> Default to undef for syncversion parameter in selinux::module 

manifests/config.pp, spec/classes/selinux_config_mode_spec.rb, spec/default_module_facts.yml
The fact is in fact called $::selinux not $::selinux_enabled.
It was not caught by the spec test because it was specified in
default_module_facts.yaml.
And there is only a WIP accetpance test for disabled to enforcing
switch which will check this too in future.
The existing acceptance tests for centos-72-x64 and 
centos-66-x64 discovered no problems with this PR.
=> Fix usage of non-existent $::selinux_enabled fact

CHANGELOG.md, metadata.json
Log diff between 0.7.0 and this PR:
a7f1de8 Release 0.7.1
c607c09 Fix usage of non-existent $::selinux_enabled fact
7e0514f Enable spec tests to delete selinux facts
53c8946 Update selinux::module inline docs to puppet-strings format
140389f Default to undef for syncversion parameter in selinux::module
25c63c6 Remove mentions of Ruby requirements in README
=> Release 0.7.1

manifests/boolean.pp, manifests/fcontext.pp, manifests/init.pp, manifests/module.pp, manifests/permissive.pp, manifests/port.pp, spec/acceptance/class_spec.rb, spec/classes/selinux_spec.rb, spec/defines/selinux_boolean_spec.rb, spec/defines/selinux_fcontext_spec.rb, spec/defines/selinux_module_spec.rb, spec/defines/selinux_permissive_spec.rb, spec/defines/selinux_port_spec.rb
This change adds ordering of resources of this module.
It enables to declare resources in different manifests without
the need to care about ordering.
=> (GH-147) Add ordering of resources

README.md
Unfortunatly the included future link was wrong.
=> Fix broken link to puppet strings documentation

manifests/port.pp, spec/defines/selinux_port_spec.rb
Only udp and tcp are valid. ipv4 and ipv6 would be valid options too
but it wasn't provided before.
This change closes #119
=> (GH-119) Don't accept udp6 and tcp6 as protocol name with selinux::port

manifests/init.pp, spec/classes/selinux_spec.rb
Until now only hiera was quieried for class module, port, fcontext, and permissive parameters. 
If anybody declared the class in puppet code they would not have been used. 
This change uses the passed parameters if hiera_hash() doesn't find values in hiera.
An additional fix is to not use selinux::fcontext with the permissive parameter.
Additional tests are now included to check if resources are created.
=> (GH-148) Use declared parameters

README.md, manifests/config.pp
This avoids configurations that could break when SELinux is enabled
again. The user will be issued a warning if they are not already
enforcing permissive or disabled mode
Offshoot of pull request #174
=> Downgrade enforcing to permissive configuration when SELinux is disabled

README.md, lib/puppet/provider/selinux_permissive/semanage.rb, lib/puppet/type/selinux_permissive.rb, manifests/permissive.pp, spec/acceptance/class_spec.rb, spec/acceptance/selinux_permissive_spec.rb, spec/classes/selinux_spec.rb, spec/defines/selinux_permissive_spec.rb, spec/unit/puppet/provider/selinux_permissive/semanage_spec.rb
This is a rather simple provider which should fix #165. 
This provider is even backwards-compatible, I think, if adding Puppet 4 types doesn't count.
There's a small corner case documented in the README where it's non-idempotent, but I didn't think it was worth complicating the parsing logic to fix.
=> Selinux permissive type

README.md, lib/facter/selinux_semanage_is_python3.rb, lib/puppet/provider/selinux_port/semanage.rb, lib/puppet/type/selinux_port.rb, lib/puppet_x/voxpupuli/selinux/semanage_ports.py, manifests/port.pp, spec/acceptance/class_spec.rb, spec/classes/selinux_spec.rb, spec/defines/selinux_port_spec.rb, spec/unit/provider/selinux_port/semanage_spec.rb
The selinux module currently handles port resources (among others) via exec resources, and this leads to various issues.
I though I'd practice a bit and implemented a selinux_port type and a semanage provider for the same which supports managing these "natively"
The code is still a work-in-progress. There are no tests, for example, since I'm not very experienced with ruby and I find the DSLs quite confusing... I did some manual testing and it seems to work as expected.
At any rate I would like some feedback before I proceed, especially on the prefetch implementation in the provider. I can't shake the feeling that there should be a better way to do it than what I currently have, but I honestly can't tell.
Using a type should fix at least #119, #164, #93 and #38
=> Add a selinux_port type and provider

metadata.json
We only can run acceptance tests against supported upstream distros.
Right now our acceptance tests run on:
* CentOS 6, 7 (compatible with RHEL 6, 7)
* Fedora 24, 25
The module stated support for CentOS 5 but actually it didn't work.
Closes #190
=> Remove support for EL5 and Fedora < 24

manifests/params.pp, metadata.json
We don't have the ability to test Amazone Linux. Amazon Linux
is similiar to CentOS or RHEL but it's not the same.
We only list systems we test with beaker acceptance tests
as supported.
=> Remove Amazon Linux support

spec/classes/selinux_package_spec.rb
These distro versions are not supported anymore.
=> Remove tests for Fedora 19-23 and CentOS 5

manifests/boolean.pp
Small PR to add types to the selinux::boolean define
I thought about typefying the restorecond manifest too, but I'm wondering if it should just be removed... It doesn't seem very useful as it is.
=> Convert selinux::boolean to puppet types

docs/_index.html, docs/file.README.html, docs/index.html, docs/puppet_class_list.html, docs/puppet_classes/selinux.html, docs/puppet_classes/selinux_3A_3Aconfig.html, docs/puppet_classes/selinux_3A_3Apackage.html, docs/puppet_classes/selinux_3A_3Aparams.html, docs/puppet_classes/selinux_3A_3Arefpolicy_package.html, docs/puppet_classes/selinux_3A_3Arestorecond.html, docs/puppet_classes/selinux_3A_3Arestorecond_3A_3Aservice.html, docs/puppet_defined_types/selinux_3A_3Aboolean.html, docs/puppet_defined_types/selinux_3A_3Afcontext.html, docs/puppet_defined_types/selinux_3A_3Afcontext_3A_3Aequivalence.html, docs/puppet_defined_types/selinux_3A_3Amodule.html, docs/puppet_defined_types/selinux_3A_3Apermissive.html, docs/puppet_defined_types/selinux_3A_3Aport.html, docs/puppet_defined_types/selinux_3A_3Arestorecond_3A_3Afragment.html, docs/puppet_providers_selinux_fcontext/semanage.html, docs/puppet_providers_selinux_fcontext_equivalence/semanage.html, docs/puppet_providers_selinux_permissive/semanage.html, docs/puppet_providers_selinux_port/semanage.html, docs/puppet_types/selinux_fcontext.html, docs/puppet_types/selinux_fcontext_equivalence.html, docs/puppet_types/selinux_permissive.html, docs/puppet_types/selinux_port.html, docs/top-level-namespace.html, manifests/init.pp, manifests/module.pp
Includes the changes in selinux::module in PR #195
=> Update strings docs

manifests/config.pp, manifests/init.pp, manifests/module.pp, manifests/params.pp, metadata.json
bumping stdlib to 4.13.1 was also requiered, to get the absolutepath
datatype
=> replace all validate functions with datatypes

README.md
Hi. This is a minor typo fix for the README. `target` -> `targeted`
Edit: Apparently my editor found some extra whitespace to tidy up also. I can fix that if you wish.
=> Fix spelling for supported type in README

manifests/exec_restorecon.pp, spec/defines/selinux_exec_restorecon_spec.rb
This wraps a restorecon exec so that it will execute after all other SELinux changes have been applied
Not yet very thorougly tested (or integrated with the fcontext define) but it should be useful enough standalone. Any comments?
=> Add a convenience wrapper for restorecon execs

lib/facter/selinux_agent_vardir.rb, manifests/params.pp, spec/default_module_facts.yml
Turns out this already existed, so our custom implementation in the module is not necessary.
I don't consider this a breaking change, since the fact is an implementation detail.
=> Make use of the stdlib puppet_vardir fact instead of a custom one

manifests/params.pp
Fedora 26 is almost upon us (it's available today as an alpha release), and it uses the same package name as Fedora 25.
=> Fedora 26 uses the same package_name as Fedora 25

manifests/config.pp, manifests/init.pp, spec/classes/selinux_config_type_spec.rb
Hi
A few fixes for selinux module:
1. Added strict mode for centos 5/6 policy
2. Fixed the case when selinux was in permissive but is set to disabled, that causes puppet try to do setenforce 0 again and again until reboot.
=> puppet3 module fixes

.travis.yml, metadata.json, spec/defines/selinux_exec_restorecon_spec.rb
* Update metadata.json to declare Puppet 5 compatability.
* Add Puppet 5.0 check in travis.yml (requires modulesync_config or .sync.yml update too)
* exclude rspec test that fails with new rspec-puppet 2.6.0 (#225)
=> Declare Puppet 5 compatability

spec/defines/selinux_exec_restorecon_spec.rb
Disabled because of a bug in rspec-puppet 2.6.0 which
is fixed with rspec-puppet 2.6.1 .
Closes #225
=> Re-enable restorecon spec test

manifests/params.pp
In the case of SELinux, Amazon Linux appears to resemble RHEL 5.
This allows the module to compile, rather than choke, on Amazon
Linux 2017.03.
Closes: #230
=> Add Amazon Linux support

README.md, metadata.json, spec/acceptance/nodesets/fedora-26-x64.yml, spec/acceptance/nodesets/fedora-27-x64.yml
Accetpance tests successfully ran on these 2 platforms.
=> Add Fedora 26 and 27 to supported distros

data/common.yaml, hiera.yaml, manifests/init.pp
Also add type definitions for hiera values and replace hiera_hash with the new lookup variant (fixing #238)
=> Add exec_restorecon to hiera calls

manifests/config.pp, spec/classes/selinux_config_mode_spec.rb
setenforce only accepts enforcing or permissive (or 0 and 1) as possible modes.
When calling the selinux module with the current mode as either enforcing or permissive and $mode => disabled, the exec change-selinux-status-to-disabled will give exit code 1. A reboot does solve this, but until that happens. each puppet run will result in a report with a corrective change.
=> Fixing change-selinux-status-to-disabled exec

manifests/config.pp, spec/classes/selinux_config_mode_spec.rb
The #245 issue was addressed by #246, but that introduced a new problem:
when mode param is set to 'disabled', runtime mode never gets changed to
'permissive' anymore.
The original problem was different: it was not wrong parameter to
setenforce, instead, the unless command was wrong, always grepping for
'disabled|disabled'.
This change uses literal modes instead of numeric for both exec *and*
unless command and removes conditinal statement added in #246 to restore
original behaviour. It also adds tests for unless param of the exec in
question.
@bjvrielink, could you please test if this works correctly in your environment?
=> Update and check runtime SELinux status correcty

spec/acceptance/class_disabled_spec.rb, spec/spec_helper_acceptance.rb
For better acceptance test coverage for enforcing to disabled. 
The test was successfull now because the SUT was in Permissive mode at the beginning instead of the expected Enforcing mode. If the suite starts with Enforcing the tests fail because it doesn't switch to permissive.
#249 makes the test green again.
=> Extend enforcing to disabled tests

manifests/config.pp
The calls to the global `$::selinux` facts were confusing given the name
of the module.
Modified all calls to `$::selinux` facts to use the `$facts` hash as
appropriate.
Fixes #258
=> Switch to "facts" hash for SELinux facts

CHANGELOG.md, metadata.json
Fixes https://github.com/voxpupuli/puppet-selinux/issues/265
Fixes https://github.com/voxpupuli/puppet-squid/pull/106
=> release 1.5.3

README.md, manifests/module.pp, spec/defines/selinux_module_spec.rb
This PR adds support for specifying a source for a precompiled policy package in the `selinux::module` defined type.
Currently mostly untested, but I'm submitting this here for review anyway. I intend to test it later today or tomorrow if I don't have time today.
=> Add support for installing pre-compiled policy packages

.fixtures.yml, .msync.yml, .travis.yml, Gemfile, metadata.json
=> modulesync 2.1.0 & add puppet 6 support

REFERENCE.md, docs/puppet_classes/selinux.html, docs/puppet_classes/selinux_3A_3Aparams.html, manifests/init.pp, manifests/params.pp, metadata.json
Note this silently adds RHEL 8 support. Because it's not tested I haven't added it to metadata.json, but the package name matches Fedora.
=> Simplify parameter handling

metadata.json
Added RedHat 8 and Fedora 30 to the supported OS list.
=> Update supported OS list in module metadata

lib/facter/selinux_python_command.rb, lib/facter/selinux_semanage_is_python3.rb, lib/puppet/provider/selinux_port/semanage.rb
Hi,
this PR makes the selinux_port helper use the platform Python interpreter if it exists. This makes it work on on RHEL 8 / CentOS 8.
The platform python interpreter is guaranteed to exist, as several RHEL components depend on it.
This has seen very light testing, but at least it didn't break my test system.
=> Fix selinux_port on RHEL 8/CentOS 8

README.md
https://voxpupuli.org/<module> is deprecated since puppet strings
produces mardown we can ship
=> fix reference documentation link

REFERENCE.md, manifests/boolean.pp, manifests/config.pp, manifests/fcontext.pp, manifests/fcontext/equivalence.pp, manifests/package.pp
=> Regenerate REFERENCE.md

README.md, manifests/boolean.pp, manifests/fcontext.pp, manifests/port.pp, spec/defines/selinux_boolean_spec.rb, spec/defines/selinux_fcontext_spec.rb, spec/defines/selinux_port_spec.rb
Fixes #286.  Puppet will no longer display a runtime error when applying a manifest on a node with selinux disabled.  These changes essentially make the `selinux::boolean`, `selinux::fcontext`, and `selinux::port` types do nothing when SELinux is disabled.
=> Avoid puppet errors when SELinux is disabled

Gemfile, lib/puppet/provider/selinux_fcontext/semanage.rb, metadata.json
Amazon Linux v2 is part of the RedHat family, but they started to use their own versioning. Because of that, the originally introduces check for older RHEL distributions thinks Amazon Linux v2 is an older version (`operatingsystemmajrelease == 2`) and tries to use `all files` instead of `a` which is not working.
n/a
=> Amazon Linux v2 should use the new fcontext filetype format

examples/enable_and_targeted.pp
Filename says "targeted", so type should also be "targeted". I guess "mls" was a copy-paste error.
=> examples/enable_and_targeted.pp: match type to filename

data/os/Debian.yaml, data/os/RedHat.yaml, manifests/init.pp, manifests/package.pp, manifests/refpolicy_package.pp, spec/classes/selinux_package_spec.rb
A sample set of methods to install setroubleshoot (and plugins).
Odds are this PR needs work, it is mostly a 'step one' towards seeing if this is a good fit here.
Fixes #327
=> Install setroubleshoot helpers

README.md, lib/facter/selinux_python_command.rb, lib/puppet/provider/selinux_port/semanage.rb, lib/puppet_x/voxpupuli/selinux/semanage_ports.py, metadata.json, test-acceptance-with-vagrant
Fixed:
* Moved the python discovery into the semanage_ports provider
* Ensure that the correct python is chosen by attempting to load the
`semanage` library
* Removed the #! line from the semanage_ports.py file to fix RPM
building
* Removed CentOS 6 support from `test-acceptance-with-vagrant` since
it will no longer function due to upstream deprecation
Changed:
* Marked the `selinux_python_command` fact as deprecated in the README
since the logic now resides in the provider itself
* Added support for Puppet 7
* Added Fedora 33 support
Fixes #335
Fixes #342 
Fixed #343
=> Deprecate selinux_python_command fact and move handling into provider

data/os/Debian.yaml, data/os/RedHat.yaml, manifests/init.pp, manifests/package.pp, spec/classes/selinux_package_spec.rb
Add a simple boolean to also load the supplemental selinux-sandbox tooling.  This tooling can help users restrict their own processes without the need to load custom policy.
None
=> Simplify loading of selinux sandbox tooling

examples/login.pp, lib/puppet/provider/selinux_login/semanage.rb, lib/puppet/type/selinux_login.rb, lib/puppet_x/voxpupuli/selinux/semanage_users.py, manifests/init.pp, manifests/login.pp
This is a PR to add basic support for selinux logins. This will allow mapping of linux users or groups to a selinux user.
Fixes #166
=> add support for selinux login

data/os/Debian.yaml, data/os/Debian/Debian/10.yaml, metadata.json
Provide default package names for Debian based systems.  Can still override for specific versions if need be.
One of my internal modules tests against Debian 11.  I didn't guard the selinux bits and noticed the package names don't have a default set for Debian.
=> Add Debian 11 support by moving the policy packages definition

manifests/init.pp, spec/classes/selinux_spec.rb
Class parameter for selinux::fcontext::equivalence elements
Fixes #353
=> Add param for selinux::fcontext::equivalence elements

manifests/fcontext/equivalence.pp, manifests/init.pp, manifests/module.pp, manifests/permissive.pp, spec/defines/selinux_fcontext_equivalence_spec.rb, spec/defines/selinux_module_spec.rb, spec/defines/selinux_permissive_spec.rb
Some selinux commands only work when selinux is enabled.  There are a few that were missed in previous updates.
=> Wrap some more commands in "if selinux is enabled"

data/os/RedHat/CentOS/5.yaml, data/os/RedHat/CentOS/6.yaml, data/os/RedHat/OracleLinux/5.yaml, data/os/RedHat/OracleLinux/6.yaml, data/os/RedHat/RedHat/5.yaml, data/os/RedHat/RedHat/6.yaml, data/os/RedHat/Scientific/5.yaml, data/os/RedHat/Scientific/6.yaml, lib/puppet/provider/selinux_fcontext/semanage.rb, metadata.json, spec/classes/selinux_package_spec.rb
cherry-picked from https://github.com/voxpupuli/puppet-selinux/pull/351
=> Drop EoL RHEL 6 support

REFERENCE.md, lib/puppet/provider/selinux_login/semanage.rb, lib/puppet/type/selinux_login.rb, lib/puppet_x/voxpupuli/selinux/semanage_ports.py, lib/puppet_x/voxpupuli/selinux/semanage_users.py, manifests/login.pp
This PR provides a small number of fixes for the `selinux::login` defined resource, including:
- A reference to Nil in the provider.prefetch method
- Changing the resource's arguments correctly shows up as changing the mapping, not creating a new one and deleting the previous version
- Additional error handling in the helper script
n/a
=> selinux::login: Miscellaneous fixes

README.md
The "Puppet 5 or later" requirement went obsolete with commit 69988c1723191f48f858a8726efdd337a8dbe0de. Let's refer to the metadata rather than try to keep this section of the README up-to-date.
=> README: refer to metadata.json in the Requirements section

files/selinux_build_module_simple.sh, manifests/module.pp, spec/defines/selinux_module_spec.rb
If module_name or module_dir had a space, this script would fail.
Also avoid existence test for the tmp dir and use mkdir -p instead.
=> selinux_build_module_simple.sh: improve quoting

manifests/refpolicy_package.pp
It seems one invocation of ensure_packages was missed in 326d5dbaad751800f18eccd80f167835c797de6a
=> use modern stdlib function

lib/puppet/provider/selinux_login/semanage.rb
`selinux::login` fails to run due to two bugs in the `selinux_login` provider.
Is presumably a typo in `each_values`
This logic used to use the title of `#{selinux_login_name}_#{selinux_user}` but has been changed to just use the `selinux_login_name` (340c17e345d09d64289d35d4b1a18d533dfd3b40).
When we check `resource = resources[provider.name]` the inconsistency means if the resource already exists we get the following error.
```
Warning: Puppet::Type::Selinux_login::ProviderSemanage: Selinux_login['user']: title does not match its login ('user_staff_u' != 'user')
Error: Could not prefetch selinux_login provider 'semanage': undefined method `provider=' for nil:NilClass
```
=> Fix `selinux_login` provider typo and title mismatch
