voxpupuli/puppet-selinux

manifests/params.pp
spec/classes/selinux_config_spec.rb
spec/classes/selinux_package_spec.rb
spec/classes/selinux_restorecond_config_spec.rb
spec/classes/selinux_restorecond_service_spec.rb
spec/classes/selinux_restorecond_spec.rb
spec/classes/selinux_spec.rb
spec/defines/selinux_boolean_spec.rb
spec/defines/selinux_fcontext_spec.rb
spec/defines/selinux_port_spec.rb
spec/defines/selinux_restorecond_fragment_spec.rb
spec/spec_helper.rb

fedora support

---

manifests/params.pp
spec/classes/selinux_spec.rb
spec/spec_helper.rb

Introduced by https://github.com/jfryman/puppet-selinux/pull/43

fix EL variant != 'RedHat' regression

---

lib/facter/selinux_custom_policy.rb

Fixes workaround, fixes #27

---

lib/facter/selinux_custom_policy.rb
spec/classes/selinux_package_spec.rb
spec/classes/selinux_restorecond_config_spec.rb
spec/defines/selinux_module_spec.rb
spec/defines/selinux_restorecond_fragment_spec.rb
tests/disable.pp

Just a couple of whitespace fixes which lets me use this module in my environment (automatic lint enforcer etc).
Thank you for a nice module.

Whitespace lint fixes

---

manifests/init.pp

Added hiera support for fcontext, boolean, module, and port.

added hiera support

---

manifests/init.pp

The parameter 'mode' is declared more than once

---

Gemfile
manifests/boolean.pp
manifests/config.pp
manifests/fcontext.pp
manifests/init.pp
manifests/module.pp
manifests/params.pp
manifests/permissive.pp
manifests/port.pp
manifests/restorecond.pp
manifests/restorecond/config.pp
tests/disable.pp
tests/enable.pp
tests/enable_and_targeted.pp
tests/minimal.pp
tests/mls.pp
tests/restorecond.pp
tests/targeted.pp

Also removal of unused parameter `module_prefix`.

add more lint checks

---

manifests/params.pp

The repository RHEL 5 & 6 uses Facter 1.6

Add support for Factor 1.6

---

manifests/fcontext.pp
spec/defines/selinux_fcontext_spec.rb

This commit allows you to ser a bool and will add the '-R- flag to restorecon. Restorecon will than recurse down the dir to restore the context.
There is also an update that will change the fcontext 'unless' clause. This could match too greedy.

Add recursion support for restorecon.

---

spec/classes/selinux_package_spec.rb

This commit removes a duplicate test that is covered not but three lines above it.
Fixes: #102

Removes duplicate package test

---

.sync.yml
.travis.yml
CHANGELOG.md
Gemfile
Rakefile
metadata.json
spec/spec_helper.rb
spec/spec_helper_methods.rb

modulesync 0.12.5

---

spec/defines/selinux_permissive_spec.rb

Fixes Issue-130 - No rspec for permissive

---

manifests/port.pp

Make a variable for the semanage port argument. Set default value to "-a".

add argument variable for selinux::port

---

manifests/init.pp

At the same time fix wrong doc of type parameter.

Update to puppet-strings doc in selinux class

---

.msync.yml
.travis.yml
CHANGELOG.md
metadata.json

Modulesync 0.16.6 & Release 0.6.0

---

manifests/config.pp
manifests/module.pp

Fixed `type` doc and `sx_mod_dir`.

Fix type doc

---

CHANGELOG.md
metadata.json

release 0.7.0

---

CHANGELOG.md
metadata.json

release 0.8.0

---

README.md

Update the README.md to include hints about known problems and
limitations to consider when working with SELinux and this module.
Related: GH-121, GH-164, GH-165

Document known problems / limitations

---

.gitignore
.msync.yml
.travis.yml

modulesync 0.19.0

---

.rubocop.yml
spec/spec_helper.rb

* change for changed rubocop yaml
* fix for new rubocop warning

Rubocop config fixes

---

manifests/boolean.pp
manifests/fcontext.pp
manifests/fcontext/equivalence.pp
manifests/init.pp
manifests/module.pp
manifests/permissive.pp
manifests/port.pp
manifests/restorecond.pp

Fix new puppet-lint complaints about ordering arrows

---

manifests/fcontext.pp
spec/defines/selinux_fcontext_spec.rb

Somehow, our testing didn't catch this one before

Fix resource reference issue when removing fcontexts

---

manifests/fcontext.pp
spec/defines/selinux_fcontext_spec.rb

Actually pass ensure to the wrapped selinux_fcontext resource

---

manifests/config.pp
spec/classes/selinux_config_type_spec.rb

Ensure the module build tmp/ directory is actually a directory

---

CHANGELOG.md
docs/_index.html
docs/file.README.html
docs/frames.html
docs/index.html
docs/js/app.js
docs/puppet_classes/selinux.html
docs/puppet_classes/selinux_3A_3Aconfig.html
docs/puppet_classes/selinux_3A_3Apackage.html
docs/puppet_classes/selinux_3A_3Aparams.html
docs/puppet_classes/selinux_3A_3Arefpolicy_package.html
docs/puppet_defined_types/selinux_3A_3Aboolean.html
docs/puppet_defined_types/selinux_3A_3Aexec_restorecon.html
docs/puppet_defined_types/selinux_3A_3Afcontext.html
docs/puppet_defined_types/selinux_3A_3Afcontext_3A_3Aequivalence.html
docs/puppet_defined_types/selinux_3A_3Amodule.html
docs/puppet_defined_types/selinux_3A_3Apermissive.html
docs/puppet_defined_types/selinux_3A_3Aport.html
docs/puppet_providers_selinux_fcontext/semanage.html
docs/puppet_providers_selinux_fcontext_equivalence/semanage.html
docs/puppet_providers_selinux_permissive/semanage.html
docs/puppet_providers_selinux_port/semanage.html
docs/puppet_types/selinux_fcontext.html
docs/puppet_types/selinux_fcontext_equivalence.html
docs/puppet_types/selinux_permissive.html
docs/puppet_types/selinux_port.html
docs/top-level-namespace.html
metadata.json

Not much new stuff, but might as well cut a release.

Release 1.1.0

---

.msync.yml
.rspec_parallel
.rubocop.yml
Gemfile
metadata.json
spec/acceptance/nodesets/archlinux-2-x64.yml
spec/acceptance/selinux_permissive_spec.rb

modulesync 0.21.3

---

CHANGELOG.md
docs/_index.html
docs/file.README.html
docs/index.html
docs/puppet_classes/selinux.html
docs/puppet_classes/selinux_3A_3Aconfig.html
docs/puppet_classes/selinux_3A_3Apackage.html
docs/puppet_classes/selinux_3A_3Aparams.html
docs/puppet_classes/selinux_3A_3Arefpolicy_package.html
docs/puppet_defined_types/selinux_3A_3Aboolean.html
docs/puppet_defined_types/selinux_3A_3Aexec_restorecon.html
docs/puppet_defined_types/selinux_3A_3Afcontext.html
docs/puppet_defined_types/selinux_3A_3Afcontext_3A_3Aequivalence.html
docs/puppet_defined_types/selinux_3A_3Amodule.html
docs/puppet_defined_types/selinux_3A_3Apermissive.html
docs/puppet_defined_types/selinux_3A_3Aport.html
docs/puppet_providers_selinux_fcontext/semanage.html
docs/puppet_providers_selinux_fcontext_equivalence/semanage.html
docs/puppet_providers_selinux_permissive/semanage.html
docs/puppet_providers_selinux_port/semanage.html
docs/puppet_types/selinux_fcontext.html
docs/puppet_types/selinux_fcontext_equivalence.html
docs/puppet_types/selinux_permissive.html
docs/puppet_types/selinux_port.html
docs/top-level-namespace.html
metadata.json

Only Puppet 5 compatablity declared. Not changes in functionality.

Release 1.2.0

---

spec/acceptance/class_disabled_spec.rb

Test disabling of SELinux

---

manifests/exec_restorecon.pp
spec/defines/selinux_exec_restorecon_spec.rb

A simple change allowing the restorecon wrapper to pass along the "force" flag.

Implement use of force option for restorecon

---

CHANGELOG.md

release 1.3.0

---

CHANGELOG.md
docs/_index.html
docs/css/style.css
docs/file.README.html
docs/frames.html
docs/index.html
docs/puppet_classes/selinux.html
docs/puppet_classes/selinux_3A_3Aconfig.html
docs/puppet_classes/selinux_3A_3Apackage.html
docs/puppet_classes/selinux_3A_3Aparams.html
docs/puppet_classes/selinux_3A_3Arefpolicy_package.html
docs/puppet_defined_types/selinux_3A_3Aboolean.html
docs/puppet_defined_types/selinux_3A_3Aexec_restorecon.html
docs/puppet_defined_types/selinux_3A_3Afcontext.html
docs/puppet_defined_types/selinux_3A_3Afcontext_3A_3Aequivalence.html
docs/puppet_defined_types/selinux_3A_3Amodule.html
docs/puppet_defined_types/selinux_3A_3Apermissive.html
docs/puppet_defined_types/selinux_3A_3Aport.html
docs/puppet_providers_selinux_fcontext/semanage.html
docs/puppet_providers_selinux_fcontext_equivalence/semanage.html
docs/puppet_providers_selinux_permissive/semanage.html
docs/puppet_providers_selinux_port/semanage.html
docs/puppet_types/selinux_fcontext.html
docs/puppet_types/selinux_fcontext_equivalence.html
docs/puppet_types/selinux_permissive.html
docs/puppet_types/selinux_port.html
docs/top-level-namespace.html
metadata.json

Release 1.5.1

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.msync.yml
.travis.yml
Gemfile
spec/acceptance/nodesets/docker/ubuntu-16.04.yml
spec/acceptance/nodesets/fedora-25-x64.yml
spec/acceptance/nodesets/fedora-26-x64.yml
spec/acceptance/nodesets/fedora-27-x64.yml
spec/spec_helper.rb

modulesync 1.9.2

---

CHANGELOG.md
REFERENCE.md
metadata.json

release 1.6.0

---

CHANGELOG.md
metadata.json

release 1.6.1

---

.github/CONTRIBUTING.md
.msync.yml
.travis.yml
Gemfile
spec/classes/coverage_spec.rb
spec/default_facts.yml
spec/spec_helper.rb

modulesync 2.2.0 and allow puppet 6.x

---

README.md

fix syntax of config_mode fact example

---

.fixtures.yml
.msync.yml
.sync.yml
Dockerfile
Gemfile
Rakefile
spec/spec_helper.rb

modulesync 2.7.0

---

lib/facter/selinux_semanage_is_python3.rb
metadata.json

Python 3 semanage is named python3-libsemanage

---

.github/CONTRIBUTING.md
.msync.yml
Gemfile
manifests/build.pp
manifests/config.pp
manifests/init.pp
manifests/package.pp
manifests/refpolicy_package.pp
spec/spec_helper.rb

modulesync 2.8.0

---

manifests/fcontext.pp

Changed double quotes to single quotes in example in comments

---

examples/fcontext_equals.pp

update example to match current version

---

CHANGELOG.md
metadata.json

Release of 3.1.0

---

examples/module.pp

Update module.pp to match current version

---

.github/SECURITY.md
.rubocop.yml
.travis.yml
Gemfile
examples/fcontext.pp
manifests/boolean.pp
manifests/build.pp
manifests/config.pp
manifests/exec_restorecon.pp
manifests/fcontext.pp
manifests/fcontext/equivalence.pp
manifests/init.pp
manifests/module.pp
manifests/package.pp
manifests/permissive.pp
manifests/port.pp

modulesync 3.0.0 + code reformatting because of puppet-lint updates

---

manifests/config.pp
manifests/module.pp

I like to run puppet-lint against my whole tree every so often.
It flagged these items.

Resolve puppet-lint

---

metadata.json

allow puppetlabs/stdlib 7

---

CHANGELOG.md
REFERENCE.md
metadata.json

Release 3.3.1

---

CHANGELOG.md
metadata.json

Release of 3.4.0

---

manifests/package.pp
metadata.json

resubmission of https://github.com/voxpupuli/puppet-selinux/pull/366

puppetlabs/stdlib: Require 9.x

---

metadata.json

Drop EoL CentOS 7/8

---

metadata.json

Drop EoL Fedora 36

---

metadata.json

Drop EoL RedHat 7 support

---

README.md

This is an alternative to #380.

README: remove legacy facts
